import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import Navbar from '@/components/ui/navbar'

const iranSans = localFont({ src: './font/iransansweb.ttf' })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' dir='rtl'>
            <body className={iranSans.className}>
                <Navbar />
                {children}
                <Toaster />
            </body>
        </html>
    )
}
